// Generated by CoffeeScript 1.3.3
(function() {
  var runner;

  runner = function() {
    var livereload, opts, path, port, resolve, server;
    livereload = require('./livereload');
    resolve = require('path').resolve;
    opts = require('opts');
    opts.parse([
      {
        short: "p",
        long: "port",
        description: "Specify the port",
        value: true,
        required: false
      }
    ].reverse(), true);
    port = opts.get('port') || 35729;
    server = livereload.createServer({
      port: port,
      debug: true
    });
    path = resolve(process.argv[2] || '.');
    console.log('Starting LiveReload for ' + path);
    return server.watch(path);
  };

  module.exports = {
    run: runner
  };

}).call(this);
